### ISSUE TITLE
wdi15 First Impression of the CLI

### ISSUE THREAD

**Issue by jsm13** [ga-wdi-lessons/cli-intro#10]
Add a comment on this issue answering:

1. How is the CLI different from the GUI?
2. What do you like / dislike about using it?
3. Compared to a GUI, in what ways might using the CLI be better or worse for developers?

**Comment by jsm13** [comment]
1. The CLI doesn't have images and a GUI has lots
2. I don't like that the command line doesn't tell me much. I like that it has a simple interface.
3. It is really easy to install tools on the command line

**Comment by mattpcaplan** [comment]
1. CLI is purely text based while GUI uses images.  

2. Like(GUI): Intuitive, easy to pick up, naturally makes sense.  Dislike(GUI): limitations to commands
Like(CLI): Many powerful options and commands not available in GUI. Dislike(CLI): initial learning barrier

3. CLI is better - because of flexibility in options.  Once CLI is well known it has an easier user interface.

**Comment by edawson1980** [comment]
1. CLI is different from GUI in that GUI is image-based, whereas CLI is text-based
2. dislikes: not being able to see immediate results, constant fear that I've broken the whole thing.
3. CLI is more efficient and feels more streamlined.

**Comment by Costle784** [comment]
1. CLI has much larger assortment of available commands. 
2. No feedback, so hard to know if your command 'worked'. 
3. CLI is more powerful, so one could theoretically do irrevocable harm to their program or machine.

**Comment by wjpurdum** [comment]
1. The CLI functions off of specific commands from the user; there is no visual representation. You can do everything from the terminal itself, rather than moving through the graphical interface. 
2. Dislikes - There is a learning curve - it requires language specific to the terminal; It's hard to understand your mistakes and correct them. Likes - speed at which you can execute commands, the specificity that you have use through the terminal language. 
3. CLI will be faster and more efficient. Maybe one of the downsides is you have less relation to the user/graphic experience of using GUI

**Comment by StormyRamsey** [comment]
1. CLI use text to navigate through directories.
2. I like learning a new way of using accessing the information on the computer. I don't dislike anything yet.
3. Yes, it was easy to install tools on the CLI, the directions made it very user friendly.

**Comment by electricflannel** [comment]
1.  CLI uses text to navigate through document structures.  GUI uses visuals to represent the tree.
2. CLI gets you closer to whats going on in below the surface.  This is good and bad because it exposes you to much more information that you may not have in the GUI.  The bad is that you need to know the syntax in order to use the extra functions.
3. Yes, I like using the CLI to install tool.

**Comment by ghost** [comment]
1. The CLI requires commands to execute, whereas the GUI is an graphical interface where you communicate with the computer by events like clicking.
2. Seems to be a powerful tool/CLI requires specific commands. 
3. Don't know.

**Comment by cancanomar** [comment]
1. The CLI has a specified text-based language that the computer recognizes. The GUI is designed with the user in mind
2. In CLI a single character could result in a different command executed
3. I like the CLI because once you get an understanding of the syntax, you can get a computer to do exactly what you want it to do.

**Comment by jkoo87** [comment]
1. CLI has nothing but commands and GUI has images.
2. CLI is simple, but you have to understand commands.
3. CLI is faster and simple in terms of installing tools.

**Comment by adamhoff** [comment]
1. The CLI is completely text-based while a GUI uses events like clicking the mouse.
2. I like that the CLI is simple but it is easy to mess up with.
3. The CLI is faster and makes it easier to access/upload files

**Comment by cconnerj** [comment]
1. CLI doesn't include graphics, but includes text, while GUI does.
2. I like the simplicity of the command line, very up front. GUI has a lot more going on
3. CLI is quicker and more straightforward when installing programs

**Comment by utamilah** [comment]
1. CLI (command line interface) requires entering commands in something like the Terminal, and the GUI (graphical user interface) allows you to interact with the computer using a mouse to click and drag things for example
2. For the CLI I don't like that the mouse is pretty much useless. I like how quickly I can access files and folders. For the GUI I hate seeing my folders and desktop get cluttered. I like pretty much everything else about the GUI.
3. CLI is wayyy better for installing things and using git.

**Comment by twelve13** [comment]
1.  GUI is dependent on icons and images, CLI is dependent on text
2.  I like that you can do certain tasks faster if you know what you're doing.  Also, it makes me feel "programmer-y".  I dislike how it's hard to read through blocks of text.
3.  Like above, you can perform tasks faster.  You could also a lot more damage though with CLI if you're not careful.

**Comment by lgmusic24** [comment]
1. CLI is not as intuitive GUI          
2.GUI is more efficient than CLI
3.CLI can show hidden files
4.Can't edit when you've changed a command in CLI unless you clear everything

**Comment by AmlakBarkon** [comment]
1.A CLI, or command-line interface, is a way to interact with a computer by typing text commands into a terminal window. A GUI, or graphical user interface, allows a user to interact with a computer by using a keyboard or mouse to manipulate visual elements on the screen.

**Comment by kwonih1020** [comment]
1. CLI has less graphics, and uses text through terminal. GUI has more graphics and uses through 'click' than texts.
2. CLI needs to be step by step, need perfection, many commands, no graphic, confused commands. GUI is simple and more familiar to people.
3. CLI is better for Github (upload), quick access, and less graphics.

**Comment by zonekid** [comment]
1. CLI uses text through the terminal to access and give commands.  GUI uses graphics/visuals to give users more user-friendly access.
2. CLI dislikes: step by step, commands has to be perfect, Many commands to memorize, no graphics.
GUI likes: Simple, more familiar, images to support
3.CLI: Better for Git Commits.  Quick access.  Less graphics so more space on the screen.
