### ISSUE TITLE
WDI 16 First Impression CLI 

### ISSUE THREAD

**Issue by nayana487** [ga-wdi-lessons/cli-intro#13]
Add a comment on this issue answering:

1. How is the CLI different from the GUI?
2. What do you like / dislike about using it?
3. Compared to a GUI, in what ways might using the CLI be better or worse for developers?

**Comment by scottpiercew** [comment]
The CLI is only text based and used for one task at a time. 
We like the ability to see the hierarchy and we dislike having to learn the exact location of files. 
The CLI is better for developers because you can perform tasks in a single window. The CLI is good for creating a blueprint for a project.

**Comment by Tchase44** [comment]
1.speed, much faster than GUI
2.dislike the clutter clutter, like the fast load speeds.
3. overall more efficient.

**Comment by daniellefricke** [comment]
1. GUI is more of an experience where the CLI is just operations. Ex: Eating in at a restaurant and getting full service versus picking up take out and leaving. Less frills.

2. GUI - like the visual aspect - it helps you navigate different operations. CLI is fast and efficient. You can do a lot in 1 window without going back and forth in different views. A negative is not knowing the commands to be effective. 

3. CLI is better as is uses less processing power and is faster for seasoned developers. It can be a hinderance for newer developers who have not used it.

**Comment by Fitssum** [comment]
CLI - takes more effort and memorization for a beginner to learn, GUI - visually intuitive or user friendly
CLI - high speed and less memory GUI - less speed and more resources
GUI - can handle more multitasking than CLI

**Comment by mjm5vp** [comment]
1) GUI is more user friendly and visually appealing. CLI can be quicker and has stricter syntax for actions.  CLI will receive a response back from the system.
2) It’s good if you know all the shortcuts.  It can be difficult since it’s less intuitive and easy to forget simple commands.  
3) Better because it’s quicker.  It has more options for direct commands and inputs.

**Comment by hyojinsarchet** [comment]
1. CLI is faster than GUI but you have to learn/memorize before using it.
2. CLI is more efficient but you need some effort to learn it. GUI is easier to use but it takes more memory.
3. CLI should be better for developers to use. Because you can save lots of time.

**Comment by jhosuedeveloper** [comment]
1. CLI -- typing commands 
    GUI--graphical interface, there is a picture, looks nicer, like every program we have know so far.
2. like GUI for games
  and I like CLI for programming.
3. CLI is much better for developers because is faster and it doesn't spend processing power as the GUI does.

**Comment by dionadk** [comment]
GUI is more user friendly that CLI
For using CLI one should know the commands to interact with the computer

In CLI its fast to create a file or directories. Also its easy for developers to trouble-shoot errors.
